version: '3.4'

services:
  # fileprocessor:
  #   build:
  #     context: ./file-processor/
  #     dockerfile: Dockerfile

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fileprocessor
    ports:
      - "5432:5432"
    volumes:
      - ./build/db:/var/lib/postgresql/data
      
  kafka:
    image: landoop/fast-data-dev:latest
    container_name: landoop-kafka
    environment:
      ADV_HOST: "localhost"  # Define o host para acesso local
      RUNTESTS: "0"          # Desativa os testes iniciais
      SAMPLEDATA: "0"        # Não gera dados de exemplo
      KAFKA_CREATE_TOPICS: "rows-to-process:1:1"
    ports:
      - "2181:2181"   # Zookeeper
      - "3030:3030"   # Landoop UI (Lenses)
      - "8081:8081"   # Schema Registry
      - "8082:8082"   # Kafka REST Proxy
      - "8083:8083"   # Kafka Connect REST API
      - "9092:9092"   # Kafka Broker
